// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdo0qcaiC3bxEUsGnG3z5MromX5DcRso',
    appId: '1:672026003621:android:f5f2d6b221d46b0d98e54c',
    messagingSenderId: '672026003621',
    projectId: 'depigraduationproject',
    databaseURL: 'https://depigraduationproject-default-rtdb.firebaseio.com',
    storageBucket: 'depigraduationproject.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKp4LeHyAOq6B3j7N2BEE6mbaB0hBa5po',
    appId: '1:672026003621:web:7a45e3491cc3bcb298e54c',
    messagingSenderId: '672026003621',
    projectId: 'depigraduationproject',
    authDomain: 'depigraduationproject.firebaseapp.com',
    databaseURL: 'https://depigraduationproject-default-rtdb.firebaseio.com',
    storageBucket: 'depigraduationproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XzuwBKLxZANV0u_R_YCSB2LJd85Hv6Y',
    appId: '1:672026003621:ios:8c56b5cbe549db8898e54c',
    messagingSenderId: '672026003621',
    projectId: 'depigraduationproject',
    databaseURL: 'https://depigraduationproject-default-rtdb.firebaseio.com',
    storageBucket: 'depigraduationproject.firebasestorage.app',
    androidClientId: '672026003621-2h2it4e3uljisdfg0u7gtnmr9efumdhu.apps.googleusercontent.com',
    iosClientId: '672026003621-l4meqb7m1f2h95mskcde1m0qf9uf1ii4.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduatedProject',
  );
}
