import 'package:cloud_firestore/cloud_firestore.dart';

class Autogenerated {
  List<PharmacyProducts>? pharmacyProducts;
  Metadata? metadata;

  Autogenerated({this.pharmacyProducts, this.metadata});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['pharmacy_products'] != null) {
      pharmacyProducts = <PharmacyProducts>[];
      json['pharmacy_products'].forEach((v) {
        pharmacyProducts!.add(PharmacyProducts.fromJson(v));
      });
    }
    metadata = json['metadata'] != null
        ? Metadata.fromJson(json['metadata'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    if (pharmacyProducts != null) {
      data['pharmacy_products'] = pharmacyProducts!
          .map((v) => v.toJson())
          .toList();
    }
    if (metadata != null) {
      data['metadata'] = metadata!.toJson();
    }
    return data;
  }
}

class PharmacyProducts {
  DateTime? createdAt;
  int? quantity;
  int? id;
  String? name;
  String? category;
  String? description;
  String? activeIngredient;
  String? dosageForm;
  String? strength;
  String? packSize;
  String? manufacturer;
  List<String>? indications;
  String? dosageInstructions;
  SideEffects? sideEffects;
  List<String>? contraindications;
  String? storage;
  bool? prescriptionRequired;
  num? priceUsd;
  num? priceEgp;
  double? rating;
  int? reviews;
  int? stockQuantity;
  String? availability;
  List<String>? images;
  bool? isFavorite;

  PharmacyProducts({
    this.createdAt,
    this.id,
    this.name,
    this.category,
    this.description,
    this.activeIngredient,
    this.dosageForm,
    this.strength,
    this.packSize,
    this.manufacturer,
    this.indications,
    this.dosageInstructions,
    this.sideEffects,
    this.contraindications,
    this.storage,
    this.prescriptionRequired,
    this.priceUsd,
    this.priceEgp,
    this.rating,
    this.reviews,
    this.stockQuantity,
    this.availability,
    this.images,
    this.isFavorite,
    this.quantity = 1,
  });

  PharmacyProducts.fromJson(Map<String, dynamic> json) {
    if (json['createdAt'] != null) {
      if (json['createdAt'] is Timestamp) {
        createdAt = (json['createdAt'] as Timestamp).toDate();
      } else if (json['createdAt'] is String) {
        createdAt = DateTime.parse(json['createdAt']);
      }
    } else {
      createdAt = null;
    }

    id = json['id'];
    name = json['name'];
    category = json['category'];
    description = json['description'];
    activeIngredient = json['active_ingredient'];
    dosageForm = json['dosage_form'];
    strength = json['strength'];
    packSize = json['pack_size'];
    manufacturer = json['manufacturer'];

    indications = json['indications'] != null
        ? List<String>.from(json['indications'])
        : [];

    dosageInstructions = json['dosage_instructions'];
    sideEffects = json['side_effects'] != null
        ? SideEffects.fromJson(json['side_effects'])
        : null;

    contraindications = json['contraindications'] != null
        ? List<String>.from(json['contraindications'])
        : [];

    storage = json['storage'];
    prescriptionRequired = json['prescription_required'];
    priceUsd = json['price_usd'] ?? 0.0;
    priceEgp = json['price_egp'] ?? 0;
    rating = (json['rating'] as num?)?.toDouble();
    reviews = json['reviews'];
    stockQuantity = json['stock_quantity'];
    availability = json['availability'];

    images = json['images'] != null ? List<String>.from(json['images']) : [];

    isFavorite = json['isFavorite'];
    quantity = json['quantity'] ?? 1;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['createdAt'] = createdAt?.toIso8601String();
    data['id'] = id;
    data['name'] = name;
    data['category'] = category;
    data['description'] = description;
    data['active_ingredient'] = activeIngredient;
    data['dosage_form'] = dosageForm;
    data['strength'] = strength;
    data['pack_size'] = packSize;
    data['manufacturer'] = manufacturer;
    data['indications'] = indications;
    data['dosage_instructions'] = dosageInstructions;
    if (sideEffects != null) {
      data['side_effects'] = sideEffects!.toJson();
    }
    data['contraindications'] = contraindications;
    data['storage'] = storage;
    data['prescription_required'] = prescriptionRequired;
    data['price_usd'] = priceUsd;
    data['price_egp'] = priceEgp;
    data['rating'] = rating;
    data['reviews'] = reviews;
    data['stock_quantity'] = stockQuantity;
    data['availability'] = availability;
    data['images'] = images;
    data['isFavorite'] = isFavorite;
    data['quantity'] = quantity;
    return data;
  }

  bool get isInStock => availability == 'in_stock';
  bool get isLowStock => availability == 'low_stock';
  bool get isOutOfStock => availability == 'out_of_stock';
}

class SideEffects {
  List<String>? common;
  List<String>? uncommon;
  List<String>? rare;

  SideEffects({this.common, this.uncommon, this.rare});

  SideEffects.fromJson(Map<String, dynamic> json) {
    common = json['common'] != null ? List<String>.from(json['common']) : [];
    uncommon = json['uncommon'] != null
        ? List<String>.from(json['uncommon'])
        : [];
    rare = json['rare'] != null ? List<String>.from(json['rare']) : [];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['common'] = common;
    data['uncommon'] = uncommon;
    data['rare'] = rare;
    return data;
  }
}

class Metadata {
  int? totalProducts;
  List<String>? currencyOptions;
  String? dataCreated;
  String? dataUpdated;
  NewFields? newFields;
  String? disclaimer;
  List<String>? categories;

  Metadata({
    this.totalProducts,
    this.currencyOptions,
    this.dataCreated,
    this.dataUpdated,
    this.newFields,
    this.disclaimer,
    this.categories,
  });

  Metadata.fromJson(Map<String, dynamic> json) {
    totalProducts = json['total_products'];
    currencyOptions = json['currency_options'] != null
        ? List<String>.from(json['currency_options'])
        : [];
    dataCreated = json['data_created'];
    dataUpdated = json['data_updated'];
    newFields = json['new_fields'] != null
        ? NewFields.fromJson(json['new_fields'])
        : null;
    disclaimer = json['disclaimer'];
    categories = json['categories'] != null
        ? List<String>.from(json['categories'])
        : [];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['total_products'] = totalProducts;
    data['currency_options'] = currencyOptions;
    data['data_created'] = dataCreated;
    data['data_updated'] = dataUpdated;
    if (newFields != null) {
      data['new_fields'] = newFields!.toJson();
    }
    data['disclaimer'] = disclaimer;
    data['categories'] = categories;
    return data;
  }
}

class NewFields {
  String? rating;
  String? reviews;
  String? stockQuantity;
  String? availability;

  NewFields({this.rating, this.reviews, this.stockQuantity, this.availability});

  NewFields.fromJson(Map<String, dynamic> json) {
    rating = json['rating'];
    reviews = json['reviews'];
    stockQuantity = json['stock_quantity'];
    availability = json['availability'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['rating'] = rating;
    data['reviews'] = reviews;
    data['stock_quantity'] = stockQuantity;
    data['availability'] = availability;
    return data;
  }
}
